# Porta do servidor
server.port=8080

# Banco de dados (H2 - banco de dados em memória)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update  # Cria/atualiza tabelas automaticamente

# Console H2 (para ver dados no banco)
spring.h2.console.enabled=true
